context:
  name: pydynamodb
  version: "0.8.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b073f99217695dcf304fcd8933e74ab97d13590af8d0d96109df6f689a3de465

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - boto3 >=1.21.0
    - botocore >=1.24.7
    - tenacity >=4.1.0
    - pyparsing >=3.0.0

tests:
  - python:
      imports:
        - pydynamodb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/passren/PyDynamoDB
  summary: Python DB API 2.0 (PEP 249) client for Amazon DynamoDB
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/passren/PyDynamoDB/wiki
  repository: https://github.com/passren/PyDynamoDB

extra:
  recipe-maintainers:
    - xylar
